# Site settings
baseURL = "https://michaela.is"
languageCode = "en-US"
title = "Michaela Jurkovicova"
paginate = 3
theme = "hugo-paper-main"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
# googleAnalytics = ""

# Copyright
copyright = "&copy; 2024 Michaela Jurkovičová"

[params]

  color = 'light'

  # Metadata for search engines and social sharing
  author = "Michaela Jurkovicova"
  description = "Welcome to Michaela Jurkovičová's website!"
  shareImage = "images/social.jpg"
  twitterHandle = "jurkovicova_"


  linkedin = 'jurkovicova'
  github = 'jurkovicova'
  avatar = 'd'
  name = 'Welcome'
  bio = 'Discover fresh content'

  # needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = false

  [services.twitter]
    disableInlineCSS = false